In [5]:
import json
import numpy
import gmaps
import random
import requests
import pandas as pd
from configg import gkey
from configo import okey
from pprint import pprint
from citipy import citipy
import matplotlib.pyplot as plt
from scipy.stats import linregress

In [40]:
#Requirement I: Create a heat map that displays the humidity for every city from WeatherPy 

#Sub-Task 1: Import cities.csv file and convert to dataframe
csv_path = "weather_data.csv"
weather_df = pd.read_csv(csv_path)

locations = weather_df[["Lat (deg)","Temp (K)"]].astype(float)
humidity = weather_df[["Humidity %"]].astype(float)

#Practice
#coord = [(23,75),(43,-100)]

#Sub-Task 2: Access gmaps
gmaps.configure(api_key=gkey)

#Sub-Task 3: Size Figure
figure_layout = {
    'width': '400px',
    'height': '300px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}
fig = gmaps.figure(layout=figure_layout)

#heat_layer = gmaps.heatmap_layer(weather_df, weights=humidity,
#                                 dissipating=False, max_intensity=100,
#                                point_radius=10)

#fig.add_layer(heat_layer)


#Sub-Task 4: Assign marker layer to a variable

#Practice
#markers = gmaps.marker_layer(coord)
#fig.add_layer(markers)
#fig

#Sub-Task 5: Add layer to the map
#fig.add_layer(markers)
#fig

#Things to rectify
    #Get gmaps working
    #Currently displaying city coordinates on gmaps, need humidity instead

   Humidity %
0        35.0
1        93.0
2        46.0
3        66.0
4        93.0
5       100.0
6       100.0
7        72.0

In [7]:
#Requirement II: Narrow down dataframe to <10-ish cities

#Sub-Task 1: Import weather data csv
#csv_path = "weather_data.csv"
#weather_data = pd.read_csv(csv_path)
#weather_data

#Sub-Task 2: Define criteria to narrow down cities
#weather_data_temp = weather_data.loc[weather_data["Temp (K)"] < 300]
#weather_data_lat = weather_data_temp.loc[weather_data_temp["Lat (deg)"] > 60]
#weather_data_refined = weather_data_lat.loc[weather_data_lat["Cloudiness %"] > 0]

,city,Lat (deg),Temp (K),Humidity %,Cloudiness %,Wind Speed (mph)
0,Paris,48.85,294.20,35,14,4.6
1,Cape Town,-33.93,283.94,93,0,1.0
2,New York,40.71,307.63,46,20,5.7
3,Sydney,-33.87,281.24,66,0,6.2
4,Moscow,55.75,290.12,93,100,2.0
5,Auckland,-36.87,286.18,100,4,3.1
6,New Delhi,28.61,300.50,100,90,5.1
7,Buenos Aires,-34.61,292.10,72,100,2.6